name: rust-build

# This workflow run tests and build for each push

on:
  pull_request:
  push:

jobs:
  rust-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Test
        run: |
          cargo check
          cargo test --all
      - name: Build
        run: |
          cargo build --release
